import jsPDF from "jspdf";

interface ReportCredential {
    username: string;
    password: string;
    url: string;
    source: string;
    severity: number;
    timestamp: string;
    stealer?: string;
    breachName?: string;
    country?: string;
    computerName?: string;
    operatingSystem?: string;
}

interface ReportData {
    domain: string;
    companyName: string;
    credentials: ReportCredential[];
    isTrial: boolean;
    generatedAt: Date;
}

function maskValue(value: string): string {
    if (!value || value.length < 4) return "****";
    return value.slice(0, 2) + "*".repeat(Math.min(value.length - 2, 8));
}

export function generateExposureReport(data: ReportData) {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    let y = 20;

    doc.setFontSize(22);
    doc.setFont("helvetica", "bold");
    doc.text("CyberHook", 20, y);
    y += 8;
    doc.setFontSize(14);
    doc.setFont("helvetica", "normal");
    doc.text("Exposure Report", 20, y);
    y += 6;
    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text(
        `Generated: ${data.generatedAt.toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" })}`,
        20,
        y,
    );
    y += 12;

    doc.setDrawColor(200);
    doc.line(20, y, pageWidth - 20, y);
    y += 10;

    doc.setTextColor(0);
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text("Company Summary", 20, y);
    y += 8;
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text(`Domain: ${data.domain}`, 20, y);
    y += 5;
    doc.text(`Company: ${data.companyName}`, 20, y);
    y += 10;

    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text("Exposure Overview", 20, y);
    y += 8;
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");

    const count = data.credentials.length;
    const countText = count >= 15 ? "15+ (sample)" : String(count);
    doc.text(`Total Compromised Credentials: ${countText}`, 20, y);
    y += 5;

    const sources = new Set(data.credentials.map((c) => c.source).filter(Boolean));
    doc.text(`Unique Sources: ${sources.size}`, 20, y);
    y += 5;

    const stealers = data.credentials.filter((c) => c.stealer).length;
    doc.text(`Via Infostealers: ${stealers}`, 20, y);
    y += 10;

    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text("Compromised Credentials", 20, y);
    y += 8;

    doc.setFontSize(8);
    doc.setFont("helvetica", "bold");
    doc.setFillColor(240, 240, 240);
    doc.rect(20, y - 4, pageWidth - 40, 8, "F");
    doc.text("Email/Username", 22, y);
    doc.text("Source", 80, y);
    doc.text("Date", 120, y);
    doc.text("Severity", 155, y);
    y += 6;

    doc.setFont("helvetica", "normal");
    for (const cred of data.credentials) {
        if (y > 270) {
            doc.addPage();
            y = 20;
        }
        const username = data.isTrial ? maskValue(cred.username) : cred.username;
        doc.text(username.substring(0, 30), 22, y);
        doc.text((cred.source || cred.stealer || "Unknown").substring(0, 20), 80, y);
        doc.text(cred.timestamp || "N/A", 120, y);
        const sevLabel =
            cred.severity >= 8
                ? "Critical"
                : cred.severity >= 5
                  ? "High"
                  : cred.severity >= 3
                    ? "Medium"
                    : "Low";
        doc.text(sevLabel, 155, y);
        y += 5;
    }

    if (count >= 15) {
        y += 5;
        doc.setFontSize(9);
        doc.setTextColor(150);
        doc.text("This report contains sample records. Contact us for the full dataset.", 20, y);
        y += 8;
    }

    y += 10;
    doc.setDrawColor(200);
    doc.line(20, y, pageWidth - 20, y);
    y += 8;
    doc.setFontSize(8);
    doc.setTextColor(120);
    doc.text(`Generated by CyberHook - ${data.generatedAt.toLocaleDateString()}`, 20, y);
    y += 4;
    doc.text("Confidential - For authorized use only", 20, y);

    const dateStr = data.generatedAt.toISOString().slice(0, 10);
    doc.save(`CyberHook_Exposure_Report_${data.domain}_${dateStr}.pdf`);
}
